// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProspOcean_Global.Persistencia;

#nullable disable

namespace ProspOcean_Global.Migrations
{
    [DbContext(typeof(ProspOceanDbContext))]
    partial class ProspOceanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProspOcean_Global.Models.Conservacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_cons");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("contato_cons");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("desc_cons");

                    b.Property<int>("EspecieId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Especie_id_esp");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("titulo_cons");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.ToTable("Conservacao");
                });

            modelBuilder.Entity("ProspOcean_Global.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_esp");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("desc_esp");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("habitat_esp");

                    b.Property<string>("NomeCientifico")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("nm_cientifico_esp");

                    b.Property<string>("NomeComum")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("nm_commum_esp");

                    b.HasKey("Id");

                    b.ToTable("Especie");
                });

            modelBuilder.Entity("ProspOcean_Global.Models.Favoritadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_fav");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EspecieId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Especie_id_esp");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Usuario_id_usu");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Favoritadas");
                });

            modelBuilder.Entity("ProspOcean_Global.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usu");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("email_usu");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("nome_usu");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("senha_usu");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProspOcean_Global.Models.Conservacao", b =>
                {
                    b.HasOne("ProspOcean_Global.Models.Especie", "Especie")
                        .WithMany("Conservacoes")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("ProspOcean_Global.Models.Favoritadas", b =>
                {
                    b.HasOne("ProspOcean_Global.Models.Especie", "Especie")
                        .WithMany("Favoritadas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProspOcean_Global.Models.Usuario", "Usuario")
                        .WithMany("Favoritadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProspOcean_Global.Models.Especie", b =>
                {
                    b.Navigation("Conservacoes");

                    b.Navigation("Favoritadas");
                });

            modelBuilder.Entity("ProspOcean_Global.Models.Usuario", b =>
                {
                    b.Navigation("Favoritadas");
                });
#pragma warning restore 612, 618
        }
    }
}
